"""empty message

Revision ID: 053d20f1f527
Revises: c1c88a25a504
Create Date: 2024-09-13 13:09:45.450231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053d20f1f527'
down_revision = 'c1c88a25a504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'invite_code', ['invite_code_id'], ['id'])

    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('inviter_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('invitee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.drop_constraint('invite_code_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['invitee_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['inviter_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('invite_code_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('used_at')
        batch_op.drop_column('invitee_id')
        batch_op.drop_column('inviter_id')
        batch_op.drop_column('code')

    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invite_code_id')

    # ### end Alembic commands ###
