"""empty message

Revision ID: 07a01caa02b9
Revises: d5cdc6791b59
Create Date: 2024-09-30 17:27:10.665826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a01caa02b9'
down_revision = 'd5cdc6791b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dapaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'invite_code', ['invite_code_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dapaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invite_code_id')

    # ### end Alembic commands ###
