"""empty message

Revision ID: 08ffb4fa5141
Revises: 2ca9b718e897
Create Date: 2024-10-06 14:37:59.830539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ffb4fa5141'
down_revision = '2ca9b718e897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dapaint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dapaint_id'], ['dapaint.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pay')
    # ### end Alembic commands ###
