"""empty message

Revision ID: 2ca9b718e897
Revises: 69b5deb42564
Create Date: 2024-10-02 15:22:35.221024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca9b718e897'
down_revision = '69b5deb42564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_winnerImg', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('foe_winnerImg', sa.String(length=500), nullable=False))
        batch_op.drop_column('vid_url')
        batch_op.drop_column('img_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('vid_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('foe_winnerImg')
        batch_op.drop_column('host_winnerImg')

    # ### end Alembic commands ###
