"""empty message

Revision ID: 31526b2f6e1d
Revises: bfb872c70ca6
Create Date: 2024-09-11 12:16:07.365837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31526b2f6e1d'
down_revision = 'bfb872c70ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['used_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('used_by_user_id')

    # ### end Alembic commands ###
