"""empty message

Revision ID: 36b21b6579bd
Revises: 31526b2f6e1d
Create Date: 2024-09-11 12:53:56.183473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36b21b6579bd'
down_revision = '31526b2f6e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_code')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['invite_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invite_code')

    op.create_table('invite_code',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('used_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['user.id'], name='invite_code_used_by_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='invite_code_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invite_code_pkey'),
    sa.UniqueConstraint('code', name='invite_code_code_key')
    )
    # ### end Alembic commands ###
