"""empty message

Revision ID: 3734e1e9ff35
Revises: 
Create Date: 2024-08-06 19:39:04.289801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3734e1e9ff35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('winstreak', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('winsByKO', sa.Integer(), nullable=True),
    sa.Column('winsBySub', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('lossesByKO', sa.Integer(), nullable=True),
    sa.Column('lossesBySub', sa.Integer(), nullable=True),
    sa.Column('disqualifications', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('da_paint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostFoeId', sa.Integer(), nullable=False),
    sa.Column('foeId', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('winnerId', sa.Integer(), nullable=True),
    sa.Column('loserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foeId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['hostFoeId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['winnerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('foeId')
    )
    op.create_table('user_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('wsh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wsh')
    op.drop_table('user_img')
    op.drop_table('da_paint')
    op.drop_table('user')
    # ### end Alembic commands ###
