"""empty message

Revision ID: 3c366869fe36
Revises: bbb663354a9d
Create Date: 2024-08-17 17:15:36.301889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c366869fe36'
down_revision = 'bbb663354a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###
