"""empty message

Revision ID: 3f84d8476c6f
Revises: c6f4c2d69f44
Create Date: 2024-07-20 22:15:10.544593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f84d8476c6f'
down_revision = 'c6f4c2d69f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('da_paint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostFoeId', sa.Integer(), nullable=False),
    sa.Column('foeId', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('winnerId', sa.Integer(), nullable=True),
    sa.Column('loserId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foeId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['hostFoeId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['winnerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('zipcode', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('birthday', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('winstreak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('winsByKO', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('winsBySub', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lossesByKO', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lossesBySub', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disqualifications', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('disqualifications')
        batch_op.drop_column('lossesBySub')
        batch_op.drop_column('lossesByKO')
        batch_op.drop_column('losses')
        batch_op.drop_column('winsBySub')
        batch_op.drop_column('winsByKO')
        batch_op.drop_column('wins')
        batch_op.drop_column('winstreak')
        batch_op.drop_column('birthday')
        batch_op.drop_column('phone')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('city')
        batch_op.drop_column('name')

    op.drop_table('da_paint')
    # ### end Alembic commands ###
