"""empty message

Revision ID: 60cb0d5ac47f
Revises: 2a155521f057
Create Date: 2024-10-14 12:50:54.436364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60cb0d5ac47f'
down_revision = '2a155521f057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('paypal_id', sa.String(length=500), nullable=True),
    sa.Column('type_of_order', sa.String(length=20), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paypal_id')
    )
    op.drop_table('user_pay')
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=False))
        batch_op.alter_column('ticket_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.drop_column('is_purchased')
        batch_op.drop_column('status')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dapaint_unlocked', sa.Boolean(), nullable=True))
        batch_op.drop_column('access_to_dapaint')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_to_dapaint', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('dapaint_unlocked')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_purchased', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ticket_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('order_id')

    op.create_table('user_pay',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dapaint_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dapaint_id'], ['dapaint.id'], name='user_pay_dapaint_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_pay_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pay_pkey')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
