"""empty message

Revision ID: 62a77d77dab2
Revises: 
Create Date: 2024-09-08 11:23:12.243646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62a77d77dab2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('num_users', sa.Integer(), nullable=True),
    sa.Column('daily_active_users', sa.Integer(), nullable=True),
    sa.Column('market_share', sa.Float(), nullable=True),
    sa.Column('matches_per_day', sa.Integer(), nullable=True),
    sa.Column('winners_per_day', sa.Integer(), nullable=True),
    sa.Column('losers_per_day', sa.Integer(), nullable=True),
    sa.Column('inactive_users_per_day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_disqualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('disqualified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('winstreak_history')
    op.drop_table('admin')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lossesByKO')
        batch_op.drop_column('winsBySub')
        batch_op.drop_column('winsByKO')
        batch_op.drop_column('disqualifications')
        batch_op.drop_column('lossesBySub')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lossesBySub', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('disqualifications', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('winsByKO', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('winsBySub', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lossesByKO', sa.INTEGER(), autoincrement=False, nullable=True))

    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('rank', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admin_pkey'),
    sa.UniqueConstraint('email', name='admin_email_key'),
    sa.UniqueConstraint('name', name='admin_name_key')
    )
    op.create_table('winstreak_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='winstreak_history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='winstreak_history_pkey'),
    sa.UniqueConstraint('user_id', name='winstreak_history_user_id_key')
    )
    op.drop_table('user_disqualification')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
