"""empty message

Revision ID: 69b5deb42564
Revises: 07a01caa02b9
Create Date: 2024-10-02 12:56:58.202527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b5deb42564'
down_revision = '07a01caa02b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dapaint', schema=None) as batch_op:
        batch_op.drop_constraint('dapaint_invite_code_id_fkey', type_='foreignkey')
        batch_op.drop_column('invite_code_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dapaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('dapaint_invite_code_id_fkey', 'invite_code', ['invite_code_id'], ['id'])

    # ### end Alembic commands ###
