"""empty message

Revision ID: 6c98282f20e1
Revises: 9f924444230f
Create Date: 2024-09-21 13:34:19.554516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c98282f20e1'
down_revision = '9f924444230f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
