"""empty message

Revision ID: 772e6ad9f82c
Revises: 36b21b6579bd
Create Date: 2024-09-11 16:08:30.681713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772e6ad9f82c'
down_revision = '36b21b6579bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tiktok_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('twitch_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('kick_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('twitter_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('twitter_url')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('kick_url')
        batch_op.drop_column('twitch_url')
        batch_op.drop_column('tiktok_url')
        batch_op.drop_column('instagram_url')

    # ### end Alembic commands ###
