"""empty message

Revision ID: 824520e56172
Revises: eb396307f50c
Create Date: 2024-10-17 14:22:44.375914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824520e56172'
down_revision = 'eb396307f50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('qr_code_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('qr_code_path',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
