"""empty message

Revision ID: 9a2435ae7886
Revises: 62a77d77dab2
Create Date: 2024-09-08 11:55:48.484246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2435ae7886'
down_revision = '62a77d77dab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastmodify', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dispute_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dispute_reported', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['lastmodify'])
        batch_op.create_foreign_key(None, 'user', ['lastmodify'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('dispute_reported')
        batch_op.drop_column('dispute_status')
        batch_op.drop_column('lastmodify')

    # ### end Alembic commands ###
