"""empty message

Revision ID: 9f924444230f
Revises: 
Create Date: 2024-09-21 12:25:21.050952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f924444230f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('zipcode', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('winstreak', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('instagram_url', sa.String(length=200), nullable=True),
    sa.Column('tiktok_url', sa.String(length=200), nullable=True),
    sa.Column('twitch_url', sa.String(length=200), nullable=True),
    sa.Column('kick_url', sa.String(length=200), nullable=True),
    sa.Column('youtube_url', sa.String(length=200), nullable=True),
    sa.Column('twitter_url', sa.String(length=200), nullable=True),
    sa.Column('facebook_url', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('advertiser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('ad_budget', sa.Float(), nullable=True),
    sa.Column('targeting_criteria', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email')
    )
    op.create_table('insight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('daily_active_users', sa.Integer(), nullable=True),
    sa.Column('winstreak_winners', sa.Integer(), nullable=True),
    sa.Column('most_popular_sport', sa.String(length=50), nullable=True),
    sa.Column('sports_market_percentage', sa.Float(), nullable=True),
    sa.Column('matches_per_day', sa.Integer(), nullable=True),
    sa.Column('inactive_users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invite_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('inviter_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_disqualification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ad_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertiser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dapaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostFoeId', sa.Integer(), nullable=False),
    sa.Column('foeId', sa.Integer(), nullable=True),
    sa.Column('fitnessStyle', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('winnerId', sa.Integer(), nullable=True),
    sa.Column('loserId', sa.Integer(), nullable=True),
    sa.Column('host_winnerImg', sa.String(length=250), nullable=True),
    sa.Column('foe_winnerImg', sa.String(length=250), nullable=True),
    sa.Column('lastmodify', sa.Integer(), nullable=True),
    sa.Column('dispute_status', sa.String(length=50), nullable=True),
    sa.Column('dispute_reported', sa.Boolean(), nullable=True),
    sa.Column('invite_code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foeId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['hostFoeId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['invite_code_id'], ['invite_code.id'], ),
    sa.ForeignKeyConstraint(['lastmodify'], ['user.id'], ),
    sa.ForeignKeyConstraint(['loserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['winnerId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lastmodify')
    )
    op.create_table('invitee_association',
    sa.Column('invite_code_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invite_code_id'], ['invite_code.id'], ),
    sa.ForeignKeyConstraint(['invitee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('invite_code_id', 'invitee_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dapaint_id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=250), nullable=False),
    sa.Column('vid_url', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dapaint_id'], ['dapaint.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dapaint_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('already_scanned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dapaint_id'], ['dapaint.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('reports')
    op.drop_table('invitee_association')
    op.drop_table('dapaint')
    op.drop_table('ad_campaign')
    op.drop_table('user_img')
    op.drop_table('user_disqualification')
    op.drop_table('notifications')
    op.drop_table('invite_code')
    op.drop_table('insight')
    op.drop_table('advertiser')
    op.drop_table('user')
    # ### end Alembic commands ###
