"""empty message

Revision ID: aa9717a32107
Revises: 053d20f1f527
Create Date: 2024-09-13 14:34:37.236910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa9717a32107'
down_revision = '053d20f1f527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitee_association',
    sa.Column('invite_code_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invite_code_id'], ['invite_code.id'], ),
    sa.ForeignKeyConstraint(['invitee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('invite_code_id', 'invitee_id')
    )
    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(None, ['inviter_id'])
        batch_op.drop_constraint('invite_code_used_by_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('invite_code_invitee_id_fkey', type_='foreignkey')
        batch_op.drop_column('invitee_id')
        batch_op.drop_column('used_at')
        batch_op.drop_column('used_by_user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_invite_code_key', type_='unique')
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_invite_code_key', ['invite_code'])

    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invitee_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('invite_code_invitee_id_fkey', 'user', ['invitee_id'], ['id'])
        batch_op.create_foreign_key('invite_code_used_by_user_id_fkey', 'user', ['used_by_user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')

    op.drop_table('invitee_association')
    # ### end Alembic commands ###
