"""empty message

Revision ID: bbb663354a9d
Revises: 3d654bfbf0fa
Create Date: 2024-08-15 18:47:19.520680

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbb663354a9d'
down_revision = '3d654bfbf0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.alter_column('date_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
