"""empty message

Revision ID: bfb872c70ca6
Revises: 9a2435ae7886
Create Date: 2024-09-09 00:52:13.977558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bfb872c70ca6'
down_revision = '9a2435ae7886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_users', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sports_market_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('number_of_winners', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('number_of_losers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inactive_users', sa.Integer(), nullable=True))
        batch_op.drop_constraint('admin_user_email_key', type_='unique')
        batch_op.drop_constraint('admin_user_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('email')
        batch_op.drop_column('num_users')
        batch_op.drop_column('inactive_users_per_day')
        batch_op.drop_column('winners_per_day')
        batch_op.drop_column('losers_per_day')
        batch_op.drop_column('rank')
        batch_op.drop_column('market_share')
        batch_op.drop_column('name')

    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_winnerId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('host_loserId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('host_winnerImg', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('foe_winnerId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('foe_loserId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('foe_winnerImg', sa.String(length=250), nullable=True))
        batch_op.drop_constraint('da_paint_foeId_key', type_='unique')
        batch_op.create_foreign_key(None, 'user', ['host_loserId'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['foe_loserId'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['host_winnerId'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['foe_winnerId'], ['id'])
        batch_op.drop_column('loserImg')
        batch_op.drop_column('winnerImg')

    with op.batch_alter_table('user_disqualification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('user_disqualification_admin_id_fkey', type_='foreignkey')
        batch_op.drop_column('admin_id')
        batch_op.drop_column('disqualified_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_disqualification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disqualified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_disqualification_admin_id_fkey', 'admin_user', ['admin_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winnerImg', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('loserImg', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('da_paint_foeId_key', ['foeId'])
        batch_op.drop_column('foe_winnerImg')
        batch_op.drop_column('foe_loserId')
        batch_op.drop_column('foe_winnerId')
        batch_op.drop_column('host_winnerImg')
        batch_op.drop_column('host_loserId')
        batch_op.drop_column('host_winnerId')

    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('market_share', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rank', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('losers_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('winners_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('inactive_users_per_day', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('num_users', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('admin_user_name_key', ['name'])
        batch_op.create_unique_constraint('admin_user_email_key', ['email'])
        batch_op.drop_column('inactive_users')
        batch_op.drop_column('number_of_losers')
        batch_op.drop_column('number_of_winners')
        batch_op.drop_column('sports_market_percentage')
        batch_op.drop_column('total_users')
        batch_op.drop_column('created_at')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
