"""empty message

Revision ID: c7c2b895ef0d
Revises: e69d37d651c8
Create Date: 2024-08-08 18:07:20.225914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c2b895ef0d'
down_revision = 'e69d37d651c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.drop_constraint('da_paint_hostFoeId_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.create_unique_constraint('da_paint_hostFoeId_key', ['hostFoeId'])

    # ### end Alembic commands ###
