"""empty message

Revision ID: d6c0ce7752b8
Revises: f66c843f09b3
Create Date: 2024-08-15 15:50:45.471943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c0ce7752b8'
down_revision = 'f66c843f09b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fitnessStyle', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('da_paint', schema=None) as batch_op:
        batch_op.drop_column('fitnessStyle')

    # ### end Alembic commands ###
